describe('Scroll Spy Clicks', () => {
  it('checks get your supplies', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('Get your supplies ready')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#get-your-supplies')
  })
  it('visits watch mars', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('Watch: Mars Base')
      .click()
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#watch-mars-base')
  })
  it('visits the c link', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('Read space suits')
      .click()
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#read-space-suits')
  })
})
