describe('Scroll Spy Clicks', () => {
  it('checks the a link', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('a')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#a')
  })
  it('visits the b link', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('b')
      .click()
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#b')
  })
  it('visits the c link', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('c')
      .click()
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#c')
  })
  it('visits the d link', () => {
    cy.visit('http://localhost:3000/')
      .get('a')
      .contains('d')
      .click()
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#d')
  })
})
