describe('Scroll Spy Scroll', () => {
  it('scrolls to b element', () => {
    cy.visit('http://localhost:3000/')
      .get('#b')
      .scrollIntoView()
      .get('a')
      .contains('b')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#b')
  })
  it('scrolls to c element', () => {
    cy.visit('http://localhost:3000/')
      .get('#c')
      .scrollIntoView()
      .get('a')
      .contains('c')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#c')
  })
  it('scrolls to d element', () => {
    cy.visit('http://localhost:3000/')
      .get('#d')
      .scrollIntoView()
      .get('a')
      .contains('d')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#d')
  })
  it('scrolls to a element', () => {
    cy.visit('http://localhost:3000/')
      .get('#a')
      .scrollIntoView()
      .get('a')
      .contains('a')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#a')
  })
})
