describe('Scroll Spy Scroll', () => {
  it('scrolls to watch mars base element', () => {
    cy.visit('http://localhost:3000/')
      .get('#watch-mars-base')
      .scrollIntoView()
      .get('a')
      .contains('Watch: Mars Base')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#watch-mars-base')
  })
  it('scrolls to d element', () => {
    cy.visit('http://localhost:3000/')
      .get('#read-space-suits')
      .scrollIntoView()
      .get('a')
      .contains('Read space suits')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#read-space-suits')
  })
  it('scrolls to get supplies', () => {
    cy.visit('http://localhost:3000/')
      .get('#get-your-supplies')
      .scrollIntoView()
      .get('a')
      .contains('Get your supplies ready')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .get('h3')
      .contains('Prepare')
      .should('have.css', 'font-weight')
      .and('match', /700/)
      .url()
      .should('eq', 'http://localhost:3000/#get-your-supplies')
  })
})
